spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/musicstreamerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    user: postgres
    password: postgres
    schemas: public
    url: jdbc:postgresql://localhost:5432/musicstreamerdb
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

music-streamer:
  security:
    jwt:
      secret: "Bb-?$zv8whu9su5WYr-wBp-HFwqP-Yd7WU-G-@w-5bw4$&38v@&fV^6SqP34CgHsAbK^bE-&EM6Qju@TbXWPTXdqM7_p!nY#ACgxjsbv2a3FUf%MCeNF?2T9C=Tw+6@&"
      type: "JWT"
      issuer: "keypopsh"
      audience: "users"
      header: "Authorization"
      path: "/"
      expireTimeSeconds: 3600
  file:
    uploadPath: "frontend/public"
    image:
      dir: "img"
      ext: "jpeg jpg png gif"
      maxSize: 5242880
    audio:
      dir: "audio"
      ext: "mp3 ogg wav"
      maxSize: 52428800
